### ISSUE TITLE
Add CSS-only background pattern (maybe animate, parallax?)

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#12]
Like here, a bit more subtle maybe…

![cssclasses-website-basics](https://cloud.githubusercontent.com/assets/53684/3840213/7fc3e496-1e1a-11e4-949c-bf6964f12904.png)

**Comment by verpixelt** [comment]
I'm on it.

**Comment by verpixelt** [comment]
Parallax as you may have seen is added. It's a bit buggy outside Chrome land. I try to fix that but it shouldn't destroy the page in any ways.

**Comment by Kriesse** [comment]
Let's call it done, looks awesome :)
