### ISSUE TITLE
Write paragraph on landing page: "Who can attend"

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#13]

**Comment by thatbettina** [comment]
Suggestion: 

*_Who can attend: *_

Learners of all levels, including beginners with absolutely no experience and advanced CSS coders (markup-ers?). 

We only ask you to respect our core values, our code of conduct (do we have one?), and bring your own laptop.

**Comment by Kriesse** [comment]
Awesome, thanks! Adding it in right now. And yes, I think we should have a Code of Conduct. Does OTS have one that we could link to? CSSconf has one, but it is a bit specific for the conference (http://2014.cssconf.eu/code-of-conduct)

**Comment by thatbettina** [comment]
You're welcome.

OTS doesn't have a general code of conduct. 

There is some stuff in the coaching guide, addressed to coaches only: http://opentechschool.github.io/slides/presentations/coaching/#intro_coaching
Like "Create a friendly atmosphere" and "Don't hit on anyone"

Why don't you add to the CSSconf's code of conduct "and at all satellite events like CSSclasses" and then we can use and link to that one?

**Comment by bastianalbers** [comment]
Looks like this can be closed?

**Comment by Kriesse** [comment]
yup, done
