### ISSUE TITLE
Make gh-pages the master branch

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#16]
… otherwise it's a bit confusing for people new to the repo.

**Comment by verpixelt** [comment]
You should be able to change this right here: https://help.github.com/articles/setting-the-default-branch 
I have no admin rights to do so.

**Comment by Kriesse** [comment]
Ah, me neither – assigning to Michael :) @frontdevde

**Comment by cssconf** [comment]
done
