### ISSUE TITLE
 Info needed for attendees to website 

### ISSUE THREAD

**Issue by thatbettina** [cssconf/CSSclasses--old#18]
Proposed text:

We're excited to have you attend our workshop.

**You should bring:**
-- a laptop
-- your laptop's charger
-- your enthusiasm and open mind
-- money for drinks and lunch

**Tools to Download:**

If you can install the following on your laptop before the workshop, that would be great. If you run into trouble, we'll help you at the workshop.

_Browsers_
You can see if you have the latest version of your browser by visiting [the whatbrowser page](http://whatbrowser.org).
[Chrome](https://www.google.com)
[Firefox](http://www.getfirefox.com)

_Text Editor_
[Sublime Text version 2](http://www.sublimetext.com/2)

**How to get to the workshop:**

The workshop is located on co.up's 3rd floor.

Co.up is a co-working space located at Adalbertstraße 8, 10999 Berlin, near the U-bahn station Kottbusser Tor. 

We're in the backyard, so study the map here to find out how to find us: http://i.imgur.com/k0Of1sg.png

At the doors please ring the bell for co.up's 3rd floor. 

After we buzz you in, please use the stairs to come find us. 

If you're lost, please call Bettina at 0163 164 7045.

**Food and Drinks:**

At 1pm we will break for lunch for an hour. You can bring something to eat, order something to be delivered, or go out to eat. There are lots of vegan and vegetarian options around us. 

Co.up has soft drinks, beer, Club Mate, and bottled water for sale. We can show our support by buying drinks from them, but you're welcome to bring your own .

**Comment by verpixelt** [comment]
I would include this on the page now. Has anyone any objections?

**Comment by verpixelt** [comment]
I've added the text to the main page.
