### ISSUE TITLE
Tutorial topic : font-family

### ISSUE THREAD

**Issue by thatbettina** [cssconf/CSSclasses--old#19]
Explain and give examples of the following:

font-family

**Comment by verpixelt** [comment]
I've added a chapter for the font-family rule. If someone please could have a look if that's okay and grammatical correct that would be just aweeesooome!!! =)

**Comment by bastianalbers** [comment]
It is pretty much perfect, but one thing: i'd leave out the whole block of invalid rules, as that might just add confusion.

**Comment by verpixelt** [comment]
Okay, I'll strip that out. Wasn't sure on it either. Thanks for your feedback.
