### ISSUE TITLE
Add team section

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#2]
At the bottom, with names and links of all organizers and coaches

**Comment by thatbettina** [comment]
Please provide list of names and links--maybe we can just import from the Google Docs after the coaches enter their links.

**Comment by verpixelt** [comment]
What would you like to link there? Homepages? Just Twitter handles?

**Comment by thatbettina** [comment]
I thought we could let each team member decide, so they can enter it themselves on the Google Docs.

**Comment by Kriesse** [comment]
:+1: 
Let's collect names and handles here:
Kristina Schneider: @kriesse
Jana Ahrens: @plique

**Comment by thatbettina** [comment]
Bettina @thatbettina

**Comment by Kriesse** [comment]
These names +links need to be added to about page
Also feel free to add more text 
@maxfell

**Comment by verpixelt** [comment]
I've also added @bastianalbers. Missing: the last name of @thatbettina .
For future additions please provide me with forename, name, twitter handle and github handle. (status: not yet pushed)

**Comment by verpixelt** [comment]
Team section is now updated on live.

**Comment by verpixelt** [comment]
@thatbettina got your name from @Kriesse ;)

**Comment by thatbettina** [comment]
Great team work @verpixelt and @Kriesse !
