### ISSUE TITLE
Print 10 copies of the CSS and HTML Cheat Sheets

### ISSUE THREAD

**Issue by thatbettina** [cssconf/CSSclasses--old#25]
https://docs.google.com/a/meneatmen.com/drawings/d/172Uni12WKPMYsyWRUUgFD4wi3YEZomr7ghS5BzAPI0w/edit?usp=sharing

https://docs.google.com/drawings/d/1VPuV_P5w_oVARAd7_970vFn40ZBJWw2MaoaB8Nb-O0g/edit?usp=sharing

**Comment by bastianalbers** [comment]
Can we just print those at co.up? My printer is broken (whose isn't?). If someone else brings these it would be cool though.

**Comment by jellea** [comment]
Let me know if we can print at co.up otherwise I'll go to a copyshop. Is 10 enough? Will take a look at the other material today and finish the sheets according to the lesson content.

**Comment by thatbettina** [comment]
@jellea The idea is that learners can share the copies, so 10 should be enough. This is also a low priority, so no worries if you don't get to print them.
