### ISSUE TITLE
Proofread workshop material with beginners' eyes to make sure everything is clear

### ISSUE THREAD

**Issue by thatbettina** [cssconf/CSSclasses--old#26]

**Comment by Ohrworm** [comment]
I read it and it seems pretty clear to me. There's a few references to topics beginners should learn more about e.g font sizes. Are there any good resources we can link to about this kind of stuff? Would be nice for people who are not complete beginners and want to find out what that's about.

**Comment by bastianalbers** [comment]
We'll add some more links in the end as this is still unfinished, but there will hopefully be some more good resources.
