### ISSUE TITLE
Bring postits, markers, name tags for 60 people

### ISSUE THREAD

**Issue by thatbettina** [cssconf/CSSclasses--old#27]

**Comment by bastianalbers** [comment]
I'll get postits + some markers, what should i get for name tags?

**Comment by bastianalbers** [comment]
Have postits and markers. Still need Name tags. Can anyone bring some tape for this?

**Comment by thatbettina** [comment]
I only have clear tape. Are postits + clear tape = name tags too ghetto?

**Comment by jellea** [comment]
I'll bring a roll of white masking tape. :)
