### ISSUE TITLE
Add text "What to expect as a coach"

### ISSUE THREAD

**Issue by thatbettina** [cssconf/CSSclasses--old#29]
Explain that coaches have time to experiment too and hack with experienced CSSers

**Comment by thatbettina** [comment]
One coach assigned to a group, 1 to 4 roughly

**Comment by Kriesse** [comment]
Add link to Coaching Guide: https://opentechschool.github.io/slides/presentations/coaching/
Add link to OTS Core Values: http://www.opentechschool.org/about.html
