### ISSUE TITLE
Advanced Topics: Collect challenges for advanced workshop attendees

### ISSUE THREAD

**Issue by thatbettina** [cssconf/CSSclasses--old#33]
This is just a collection of ideas of topics that we can suggest to workshop attendees who are too advanced for the basic workshop. No need to add them to the workshop materials – just collect them here (or on a separate page?) so that we have some backup ideas and links.
### Draw with CSS only

Draw shapes! draw… vegetables! devices!
Example: http://marvelapp.github.io/devices.css/
### CSS Flags

https://github.com/hagenburger/css-flags
### Transitions

Blur navigation: http://tympanus.net/codrops/2011/10/19/blur-menu-with-css3-transitions/
### Transform

Perspective navigation: http://tympanus.net/codrops/2013/12/18/perspective-page-view-navigation/
### Gradients

http://css-tricks.com/css3-gradients/

**Comment by jellea** [comment]
added some new links
