### ISSUE TITLE
Bug: Two scrollbars

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#37]
![image](https://cloud.githubusercontent.com/assets/53684/3931779/f5be124e-245e-11e4-82d7-f797b37c2ffb.png)

**Comment by verpixelt** [comment]
Yep that's an issue with the parallax scrolling I'm still struggling with. I try to fix it asap.

**Comment by verpixelt** [comment]
Should be fixed now ;)
