### ISSUE TITLE
Add download links to browsers and editors

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#4]
for both windows and mac

**Comment by thatbettina** [comment]
For Sublime Text should we use version 2 or 3?
http://www.sublimetext.com/

**Comment by verpixelt** [comment]
This doesn't matter for the stuff we'll do, but I would prefer to stick to the stable version 2(Version 3 seems to be stable on Mac, too (I'm using it for a while now), but I don't know about Windows).

**Comment by thatbettina** [comment]
I am for the stable version, but I think it depends on what the coaches want to use.

**Comment by verpixelt** [comment]
The difference between ST2 & ST3 won't matter for a beginner workshop so let's just stick to version 2(if nobody complains).

**Comment by stryju** [comment]
do you also plan on introducing to `emmet` (formerly `zen`)?

**Comment by verpixelt** [comment]
I would highly disagree on this(at least for the beginner workshop). Love this tool but I think everyone should be able to write simple HTML/CSS without any helpers in particular beginners. We could show this maybe in an advanced course!?

**Comment by stryju** [comment]
:+1: for advanced course

**Comment by thatbettina** [comment]
Closed by #18
