### ISSUE TITLE
Tutorial topic: transitions and transforms

### ISSUE THREAD

**Issue by trodrigues** [cssconf/CSSclasses--old#48]
We already have a section explaining :hover, so adding a simple thing about a transition and transform is fairly straightforward. Also people saw the spinning circle thing and everyone wants to know how to do that.

Something such as:

```
<div class="selector">hello</div>

.selector {
  width: 200px;
  height: 200px;
  border: 2px solid green;
  transform: rotate(10deg);
  transition: transform 2s;
}

.selector:hover {
  transform: rotate(180deg);
}
```

**Comment by bastianalbers** [comment]
I added a transition section but it gets fairly complicated in the end. Maybe needs some more work...

**Comment by bastianalbers** [comment]
I'll close this for now. If we want an explanation for transforms, we should open a new task. Bettina quickly proofread the transform section and it seems to be fine.
