### ISSUE TITLE
Put up new dates / rsvp info

### ISSUE THREAD

**Issue by bastianalbers** [cssconf/CSSclasses--old#52]
We have the co.up on saturday, sep 13. Need to think about when/how to open up to make people RSVP...

**Comment by Ohrworm** [comment]
maybe good to announce at the beginning of september when everyone has that back to school feeling.

**Comment by bastianalbers** [comment]
New date is there, RSVP needs to be done...

**Comment by elf-pavlik** [comment]
i follow on http://cssclasses.cssconf.eu/ link _information for attendees_
it gets me to http://cssclasses.cssconf.eu/attendees/ where i follow _signed up here_
which takes me to old event http://www.meetup.com/opentechschool-berlin/events/199567452/

while not noticing on first page _RSVP for our 2nd event on Sept 13 will open soon._ it made me bit confused :confused:

**Comment by verpixelt** [comment]
Thanks for the heads up. We should remove this link as long as we haven't setup the new RSVP.

**Comment by bastianalbers** [comment]
Fixed this for now with a hint to our twitter account so people don’t miss out once we open registration.

**Comment by bastianalbers** [comment]
Pushed the RSVP-ready site, although registration doesn't start before tomorrow at 10. But i'll have to make my daughter her oatmeal in the morning and have a long debate about how much sugar is allowed in there, so i think pushing this now is fine.
