### ISSUE TITLE
Inline and Block Boxes

### ISSUE THREAD

**Issue by thatbettina** [cssconf/CSSclasses--old#56]
Block class does nothing, and inline class does nothing. It's confusing! 

Suggestion from learner: rename class "potatoes".

**Comment by verpixelt** [comment]
I don't get it. What exactly do you mean? Can you please point me to the exact spot?!

**Comment by thatbettina** [comment]
@verpixelt Sorry for the opaque notes on the issue. I was taking notes as I was working through the learning materials. I think the material is teaching the difference between inline versus block, so the classes were called .inline and .block But a span is inline already and a div is a block already, so those classes seemed superfluous. I get that the classes are there to make the examples visible, so maybe we could rename something totally other than inline, block, etc. so that it's clear that these classes are not the point of this section of learning materials. 

Is that still opaque?

**Comment by Kriesse** [comment]
Closing, i think that entire section needs and update.
