### ISSUE TITLE
Work on workshop material

### ISSUE THREAD

**Issue by lislis** [cssconf/CSSclasses--old#6]
Plan was, I think, to take a look at the Open Tech School HTML/CSS workshop materials and modify them to fit our needs. 
I would come to the OTS Web Frontend Co-learning (http://www.meetup.com/opentechschool-berlin/events/191929812/) event this evening and work on it.

**Comment by bastianalbers** [comment]
Did you do/plan any work? I heard you were there and Bettina was there as well, i just don't want to duplicate anything when i start today.

**Comment by lislis** [comment]
I just took a look at what it already there because I wasn't familiar with the OTS material for their workshop. But I didn't do any real work. I would show up again this Wednesday to do some real stuff though.

**Comment by verpixelt** [comment]
I'll check on the tuts.plus material(which I've linked in the Google doc) in the next few days to see what we can use.

**Comment by bastianalbers** [comment]
If anyone can come on wednesday evening: i'll be at co.up on the 5th floor again from around 7.

**Comment by lislis** [comment]
I'll be there! For real :)

**Comment by Kriesse** [comment]
Closing, it's almost there. Now tracking in separate issues :)
