### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#60]
to make it easier for everyone to set up jekyll etc and contribute

**Comment by lukaszklis** [comment]
I believe that #64 closes this one (unless README needs more improvement).

**Comment by lukaszklis** [comment]
We should add more details on how to get ruby installed cross-platform. We could provide links to the installation guidelines from Ruby's official website: https://www.ruby-lang.org/en/documentation/installation/
