### ISSUE TITLE
link debug bookmarklet

### ISSUE THREAD

**Issue by afknapping** [cssconf/CSSclasses--old#61]
i know there are several – which one was used for this image?

![image](https://cloud.githubusercontent.com/assets/170145/7366848/5641b0b6-ed9b-11e4-8430-505194652b80.png)

**Comment by Kriesse** [comment]
@filtercake Feel free to pick your favorite one and add it, maybe replace the screenshot as well?

**Comment by afknapping** [comment]
:+1: 

[108 byte CSS Layout Debugger](https://gist.github.com/addyosmani/fd3999ea7fce242756b1#tag-specific-layout-debugging-in-82-bytes)

**Comment by verpixelt** [comment]
Actually I'v used none, if I remember it correctly.

```
* { border: 1px solid tomato;

  &:before,
  &:after {
    border: inherit;
  }
}
```

;)
