### ISSUE TITLE
Add tutorial on :nth-child selectors

### ISSUE THREAD

**Issue by lislis** [cssconf/CSSclasses--old#71]

**Comment by rafalbromirski** [comment]
might be useful: 
- http://codepen.io/sacha/full/cAJEo
- http://nthmaster.com/
- http://nth-test.com/

**Comment by bastianalbers** [comment]
these are awesome! I think :nth-child would be a nice addition to the stuff we already explain.

**Comment by Kriesse** [comment]
@bastianalbers reviewed and proofread, looks awesome! :+1:
