### ISSUE TITLE
Add tutorial on positioning

### ISSUE THREAD

**Issue by lislis** [cssconf/CSSclasses--old#72]
would be nice if this would not go deep into layouts

**Comment by rafalbromirski** [comment]
http://learnlayout.com/position.html

**Comment by bastianalbers** [comment]
Yes, learnlayout explains this perfectly. We should either link to it or pull some of it into the tutorial. I think we definitely need to explain why you would _want_ to know about it.

**Comment by Kriesse** [comment]
Agreed, we could walk through http://learnlayout.com/ with everyone interested in that topic. I’ll close this issue and add a new one to include learnlayout :)
