### ISSUE TITLE
Design to narrow for side-by-side code view

### ISSUE THREAD

**Issue by bastianalbers** [cssconf/CSSclasses--old#8]
Hey, i like the centered block in the middle, but it seems very narrow, especially since i thought it would be nice to have a side-by-side commented code view. This won't work on small screens anyways, but on bigger'ish screens it is a nicer way to show what the code is about i'd say.

**Comment by verpixelt** [comment]
Hey Bastian, I narrowed it down for the sake of readability(ideal line length). I wasn't aware of what kind of content is planned for the page. Could you or someone who knows what kinda page layouts we'll have provide me with one or two rough sketches(large viewport would do the job).

**Comment by bastianalbers** [comment]
I think we should still narrow down for readability somehow, but i think with the way it is now you already see in the learning materials what i meant. I have no good idea how to change this except we could do a container around that with negative margin-left maybe? Don't know, hmm...

**Comment by verpixelt** [comment]
I will get onto it tomorrow ;) and find a good solution for it.
