### ISSUE TITLE
Prepare feedback form

### ISSUE THREAD

**Issue by Kriesse** [cssconf/CSSclasses--old#81]
Prepare a way to collect feedback from attendees.

@luciefocus @Ohrworm I think you had a plan for this?

**Comment by Lucie-H** [comment]
I created this form to print so attendees can fill it out at the end of the workshop: https://docs.google.com/document/d/1zY16g_rvCuB5ehBeFmSC03_tCS2zbk-k2bAfk9Pj5SY/edit# 
Also did a google form to post at meetup: http://goo.gl/forms/3FbUBypWzO

**Comment by Kriesse** [comment]
Thanks @Lucie-H, this is awesome! Closing the issue.
